apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: pharmago
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'otlp-collector'
        metrics_path: /metrics
        static_configs:
          - targets: ['otlp-collector:8889']
      
      - job_name: 'users-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['pharmago-users-service:80']
      
      - job_name: 'pharmacy-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['pharmago-pharmacy-service:80']
      
      - job_name: 'api-gateway'
        metrics_path: /metrics
        static_configs:
          - targets: ['pharmago-api-gateway:80']

      - job_name: 'node-exporter'
        metrics_path: /metrics
        static_configs:
          - targets: ['node-exporter:9100']

      # cAdvisor: métricas por contenedor/pod (para ver impacto de chaos)
      - job_name: 'kubernetes-cadvisor'
        kubernetes_sd_configs:
        - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
        - source_labels: [__meta_kubernetes_node_name]
          target_label: node
        - replacement: kubernetes-cadvisor
          target_label: job

