apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharmago-ui
  namespace: pharmago
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pharmago-ui
  template:
    metadata:
      labels:
        app: pharmago-ui
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values: [frontend, all]
      containers:
      - name: pharmago-ui
        image: pharmago-ui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10

