apiVersion: v1
kind: Service
metadata:
  name: otlp-collector
  namespace: pharmago
spec:
  selector:
    app: otlp-collector
  ports:
  - port: 4317
    targetPort: 4317
    protocol: TCP
    name: otlp-grpc
  - port: 8889
    targetPort: 8889
    protocol: TCP
    name: prometheus
  type: ClusterIP

